PRAGMA foreign_keys = ON;

CREATE TRIGGER DIMINUIR_VAGAS
BEFORE INSERT ON INSCRITO_EM_CURSO
FOR EACH ROW
WHEN EXISTS(
    SELECT * FROM CURSO
    WHERE CURSO.idCurso = NEW.idCurso
    AND CURSO.vagas > 0
)
BEGIN
	UPDATE CURSO 
    SET vagas = vagas - 1
    WHERE CURSO.idCurso = NEW.idCurso;
END;

CREATE TRIGGER AVOID_ADDING_INSCRICAO
BEFORE INSERT ON INSCRITO_EM_CURSO
FOR EACH ROW
WHEN EXISTS(
    SELECT * FROM CURSO
    WHERE CURSO.idCurso = NEW.idCurso
    AND CURSO.vagas = 0
)
BEGIN
	SELECT RAISE(ABORT, "Não há vagas neste curso");
END;

CREATE TRIGGER AUMENTAR_VAGAS
BEFORE DELETE ON INSCRITO_EM_CURSO
FOR EACH ROW
WHEN EXISTS(
    SELECT * FROM CURSO
    WHERE CURSO.idCurso = OLD.idCurso
)
BEGIN
	UPDATE CURSO 
    SET vagas = vagas + 1
    WHERE CURSO.idCurso = OLD.idCurso;
END;

