PRAGMA foreign_keys = ON;

SELECT * FROM INSCRITO_EM_TURMA;

INSERT INTO INSCRITO_EM_TURMA VALUES(1,2);

SELECT * FROM INSCRITO_EM_TURMA;

DELETE FROM INSCRITO_EM_TURMA WHERE idEstudante = 1 AND idTurma = 2;