PRAGMA foreign_keys = ON;

SELECT MAX(notaFinal), ESTUDANTE.nome, UNIDADE_CURRICULAR.nome FROM INSTANCIA_DE_AVALIACAO
JOIN AVALIACAO USING(idAvaliacao)
JOIN ESTUDANTE USING(idEstudante)
JOIN UNIDADE_CURRICULAR USING(idCadeira)
GROUP BY UNIDADE_CURRICULAR.idCadeira